### PR TITLE
Feature/wizard header

### PR DESCRIPTION
**Pull request by jpushkarskaya**
UI improvements
Progress Bars

### CODE REVIEW

**Comment by jkoryf** [comment]
Nice improvements!

Two notes:
- The FAB in Wizard screens shows a little bit cropped

screen shot 2016-11-29 at 4 03 17 pm

- Last FAB in Wizard seems like it's changing position while on progress

fab

**Comment by jpushkarskaya** [comment]
So weird! I'm not seeing either of these issues locally

**Comment by jpushkarskaya** [comment]
Weird, neither of these things issues happen locally. What API are you using?

**Comment by jkoryf** [comment]
API 21

**Review by emaccaull — APPROVED** [review]
Looking good on my device

**Pull request merged**
